service: api
frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  memorySize: 128
  logRetentionInDays: 1
  httpApi:
    cors: true

  environment:
    ALLOWEDORIGIN: http://localhost:4200


custom:
  # payment: ${ssm:/aws/reference/secretsmanager/dev/razorpay}
  serverless-offline:
    httpPort: 3001


functions:
  calorieCalculate: 
    handler: caloriecalulate.handler
    events:
      - httpApi:
          path: /diet/calorieCalculate
          method: post


  
plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-webpack


